"""empty message

Revision ID: 28c135e2ed19
Revises: 
Create Date: 2018-07-27 12:07:17.116995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c135e2ed19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('td_company',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name_kr', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('name_zh', sa.String(length=128), nullable=True),
    sa.Column('registrationNumber', sa.String(length=64), nullable=True),
    sa.Column('businessRegistrationUrl', sa.String(length=64), nullable=True),
    sa.Column('addr_kr', sa.String(length=64), nullable=True),
    sa.Column('addr_en', sa.String(length=64), nullable=True),
    sa.Column('addr_zh', sa.String(length=64), nullable=True),
    sa.Column('telephone', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('delegator_kr', sa.String(length=64), nullable=True),
    sa.Column('delegator_en', sa.String(length=64), nullable=True),
    sa.Column('delegator_zh', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('dtRegistered', sa.String(length=64), nullable=True),
    sa.Column('dtModified', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.Column('ci', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('description_kr', sa.String(length=128), nullable=True),
    sa.Column('description_en', sa.String(length=128), nullable=True),
    sa.Column('description_zh', sa.String(length=128), nullable=True),
    sa.Column('tntLogoImgUrl', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('td_company')
    # ### end Alembic commands ###
