"""empty message

Revision ID: 5e69e5d5ed6b
Revises: 
Create Date: 2018-07-30 10:15:43.432838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e69e5d5ed6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_td_account_companyCode'), 'td_account', ['companyCode'], unique=False)
    op.drop_index('ix_td_account_companyCode', table_name='td_account')
    op.alter_column('td_admin', 'dtModified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('td_admin', 'dtRegistered',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('td_admin', 'id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('td_admin', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('td_admin', 'pwd',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('td_admin', 'role',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=True)
    op.alter_column('td_admin', 'state',
               existing_type=mysql.ENUM('Registered', 'Deleted', 'Paused'),
               nullable=True)
    op.alter_column('td_admin', 'telephone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_td_admin_role'), 'td_admin', ['role'], unique=False)
    op.drop_index('idx_td_admin_02', table_name='td_admin')
    op.create_foreign_key(None, 'td_admin', 'tc_role', ['role'], ['code'])
    op.alter_column('td_company', 'addr_kr',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('td_company', 'ci',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('td_company', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('td_company', 'delegator_kr',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('td_company', 'description_kr',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('td_company', 'dtModified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('td_company', 'dtRegistered',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('td_company', 'modifier',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('td_company', 'name_kr',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('td_company', 'registrant',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('td_company', 'registrationNumber',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('td_company', 'state',
               existing_type=mysql.ENUM('Registered', 'Deleted', 'Paused'),
               nullable=True,
               existing_server_default=sa.text("'Registered'"))
    op.alter_column('td_company', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_td_company_modifier'), 'td_company', ['modifier'], unique=False)
    op.create_index(op.f('ix_td_company_registrant'), 'td_company', ['registrant'], unique=False)
    op.drop_index('idx_td_company_02', table_name='td_company')
    op.drop_index('idx_td_company_03', table_name='td_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_td_company_03', 'td_company', ['modifier'], unique=False)
    op.create_index('idx_td_company_02', 'td_company', ['registrant'], unique=False)
    op.drop_index(op.f('ix_td_company_registrant'), table_name='td_company')
    op.drop_index(op.f('ix_td_company_modifier'), table_name='td_company')
    op.alter_column('td_company', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('td_company', 'state',
               existing_type=mysql.ENUM('Registered', 'Deleted', 'Paused'),
               nullable=False,
               existing_server_default=sa.text("'Registered'"))
    op.alter_column('td_company', 'registrationNumber',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('td_company', 'registrant',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('td_company', 'name_kr',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('td_company', 'modifier',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('td_company', 'dtRegistered',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('td_company', 'dtModified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('td_company', 'description_kr',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('td_company', 'delegator_kr',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('td_company', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('td_company', 'ci',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('td_company', 'addr_kr',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'td_admin', type_='foreignkey')
    op.create_index('idx_td_admin_02', 'td_admin', ['role'], unique=False)
    op.drop_index(op.f('ix_td_admin_role'), table_name='td_admin')
    op.alter_column('td_admin', 'telephone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('td_admin', 'state',
               existing_type=mysql.ENUM('Registered', 'Deleted', 'Paused'),
               nullable=False)
    op.alter_column('td_admin', 'role',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False)
    op.alter_column('td_admin', 'pwd',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('td_admin', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('td_admin', 'id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('td_admin', 'dtRegistered',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('td_admin', 'dtModified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index('ix_td_account_companyCode', 'td_account', ['companyCode'], unique=False)
    op.drop_index(op.f('ix_td_account_companyCode'), table_name='td_account')
    # ### end Alembic commands ###
