"""empty message

Revision ID: 6b9de907f744
Revises: 
Create Date: 2018-07-31 15:52:48.951671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b9de907f744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tc_result',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.CHAR(length=4), nullable=False),
    sa.Column('msg_kr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('msg_en', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('msg_zh', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('msg', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tc_role',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.TINYINT(display_width=4), nullable=True),
    sa.Column('name_kr', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_kr_forAccount', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_en_forAccount', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_zh_forAccount', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('isIcraft', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('code')
    )
    op.create_table('td_black_list',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pushToken', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('blType', mysql.ENUM('C', 'O'), nullable=False),
    sa.Column('delYN', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pushToken')
    )
    op.create_index(op.f('ix_td_black_list_idx'), 'td_black_list', ['idx'], unique=False)
    op.create_table('td_location_term',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('termUrl', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Published'), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=True),
    sa.Column('dtPublished', mysql.DATETIME(), nullable=True),
    sa.Column('dtDeleted', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('version')
    )
    op.create_table('td_model',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown'), nullable=False),
    sa.Column('resolution', mysql.TEXT(), nullable=True),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_td_model_osType'), 'td_model', ['osType'], unique=False)
    op.create_index(op.f('ix_td_model_name'), 'td_model', ['name'], unique=True)
    op.create_table('td_service_term',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('appTagType', mysql.CHAR(length=1), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('termUrl', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Published'), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=True),
    sa.Column('dtPublished', mysql.DATETIME(), nullable=True),
    sa.Column('dtDeleted', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('version')
    )
    op.create_table('tl_login',
    sa.Column('idx', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('resultCode', mysql.CHAR(length=4), nullable=False),
    sa.Column('dtAttempted', mysql.DATETIME(), nullable=False),
    sa.Column('remoteAddr', mysql.VARCHAR(length=23), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('ts_active_unique_count',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('companyCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('appTagType', mysql.CHAR(length=1), nullable=False),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown'), nullable=False),
    sa.Column('date', mysql.CHAR(length=8), nullable=False),
    sa.Column('active_count', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('unique_count', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cert_unique_count', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('regApp_count', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('registerDt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_ts_active_unique_count_companyCode'), 'ts_active_unique_count', ['companyCode'], unique=False)
    op.create_index(op.f('ix_ts_active_unique_count_osType'), 'ts_active_unique_count', ['osType'], unique=False)
    op.create_index(op.f('ix_ts_active_unique_count_date'), 'ts_active_unique_count', ['date'], unique=False)
    op.create_table('ts_cert_report_count',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('companyCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('tagType', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG', 'RANDOMTAG', 'SQRTAG'), nullable=True),
    sa.Column('tagCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown'), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('date', mysql.CHAR(length=8), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('registerDt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_ts_cert_report_count_companyCode'), 'ts_cert_report_count', ['companyCode'], unique=False)
    op.create_index(op.f('ix_ts_cert_report_count_osType'), 'ts_cert_report_count', ['osType'], unique=False)
    op.create_index(op.f('ix_ts_cert_report_count_tagCode'), 'ts_cert_report_count', ['tagCode'], unique=False)
    op.create_index(op.f('ix_ts_cert_report_count_date'), 'ts_cert_report_count', ['date'], unique=False)
    op.create_index(op.f('ix_ts_cert_report_count_type'), 'ts_cert_report_count', ['type'], unique=False)
    op.create_table('td_admin',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pwd', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('role', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('dtLastConnected', mysql.DATETIME(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('failCount', mysql.SMALLINT(display_width=6), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['tc_role.code'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_td_admin_role'), 'td_admin', ['role'], unique=False)
    op.create_table('td_banner',
    sa.Column('idx', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('bannerID', mysql.CHAR(length=10), nullable=False),
    sa.Column('bannerName', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('sizeType', mysql.ENUM('DEFAULT', 'WXGA'), nullable=False),
    sa.Column('imageUrl', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('linkUrl', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('interval', mysql.INTEGER(display_width=6), nullable=False),
    sa.Column('dtStart', mysql.DATETIME(), nullable=False),
    sa.Column('dtEnd', mysql.DATETIME(), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registrant'], ['td_admin.id'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('td_company',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('name_kr', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('registrationNumber', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('businessRegistrationUrl', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('addr_kr', mysql.TEXT(), nullable=False),
    sa.Column('addr_en', mysql.TEXT(), nullable=True),
    sa.Column('addr_zh', mysql.TEXT(), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fax', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('delegator_kr', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('delegator_en', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('delegator_zh', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('ci', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('description_kr', mysql.TEXT(), nullable=False),
    sa.Column('description_en', mysql.TEXT(), nullable=True),
    sa.Column('description_zh', mysql.TEXT(), nullable=True),
    sa.Column('tntLogoImgUrl', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registrant'], ['td_admin.id'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_td_company_modifier'), 'td_company', ['modifier'], unique=False)
    op.create_index(op.f('ix_td_company_registrant'), 'td_company', ['registrant'], unique=False)
    op.create_table('td_tag_version',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('version', mysql.CHAR(length=11), nullable=False),
    sa.Column('type', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG', 'RANDOMTAG', 'SQRTAG'), nullable=False),
    sa.Column('name_kr', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('name_zh', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('state', mysql.ENUM('Enalbe', 'Disable', 'Deleted'), nullable=False),
    sa.Column('width', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('height', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registrant'], ['td_admin.id'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('version')
    )
    op.create_table('td_account',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pwd', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name_kr', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=False),
    sa.Column('role', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=True),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=True),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtModified', mysql.DATETIME(), nullable=True),
    sa.Column('dtLastConnected', mysql.DATETIME(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('failCount', mysql.SMALLINT(display_width=6), nullable=True),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.ForeignKeyConstraint(['role'], ['tc_role.code'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_td_account_companyCode'), 'td_account', ['companyCode'], unique=False)
    op.create_index(op.f('ix_td_account_name_kr'), 'td_account', ['name_kr'], unique=False)
    op.create_index(op.f('ix_td_account_phone'), 'td_account', ['phone'], unique=False)
    op.create_index(op.f('ix_td_account_role'), 'td_account', ['role'], unique=False)
    op.create_table('td_app',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.CHAR(length=10), nullable=True),
    sa.Column('name_kr', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name_en', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('version', mysql.CHAR(length=11), nullable=False),
    sa.Column('type', mysql.ENUM('LIB', 'APP'), nullable=False),
    sa.Column('tagType', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG', 'RANDOMTAG', 'SQRTAG'), nullable=True),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('dtPublished', mysql.DATETIME(), nullable=True),
    sa.Column('attachedPath', mysql.TEXT(), nullable=True),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'All'), nullable=False),
    sa.Column('state', mysql.ENUM('Enable', 'Disable', 'Deleted'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('limitCertHour', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('limitCertCnt', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('updateUrl', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registrant'], ['td_admin.id'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_td_app_companyCode'), 'td_app', ['companyCode'], unique=False)
    op.create_index(op.f('ix_td_app_code'), 'td_app', ['code'], unique=False)
    op.create_index(op.f('ix_td_app_modifier'), 'td_app', ['modifier'], unique=False)
    op.create_index(op.f('ix_td_app_registrant'), 'td_app', ['registrant'], unique=False)
    op.create_table('td_holotag',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.CHAR(length=10), nullable=False),
    sa.Column('name_kr', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('attachType', mysql.ENUM('LABELBOX', 'POUCH', 'POUCH_PRINT'), nullable=True),
    sa.Column('certOverCnt', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('certOverManyCnt', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('sourceImage', mysql.TEXT(), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('mappingCode', mysql.CHAR(length=11), nullable=False),
    sa.Column('sqrUrl', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('hVersion', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('sqrVer', mysql.INTEGER(display_width=2), nullable=False),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.ForeignKeyConstraint(['hVersion'], ['td_tag_version.version'], ),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registrant'], ['td_admin.id'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_td_holotag_companyCode'), 'td_holotag', ['companyCode'], unique=True)
    op.create_index(op.f('ix_td_holotag_hVersion'), 'td_holotag', ['hVersion'], unique=False)
    op.create_index(op.f('ix_td_holotag_mappingCode'), 'td_holotag', ['mappingCode'], unique=False)
    op.create_index(op.f('ix_td_holotag_modifier'), 'td_holotag', ['modifier'], unique=False)
    op.create_index(op.f('ix_td_holotag_registrant'), 'td_holotag', ['registrant'], unique=False)
    op.create_table('td_retailer',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('rtid', mysql.CHAR(length=10), nullable=False),
    sa.Column('name_kr', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name_en', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name_zh', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('headerquarterYN', mysql.ENUM('Y', 'N'), nullable=False),
    sa.Column('registrant', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtModified', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_td_retailer_companyCode'), 'td_retailer', ['companyCode'], unique=False)
    op.create_index(op.f('ix_td_retailer_rtid'), 'td_retailer', ['rtid'], unique=False)
    op.create_table('th_certification',
    sa.Column('idx', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('deviceID', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('tagType', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG', 'RANDOMTAG', 'SQRTAG'), nullable=True),
    sa.Column('tagCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('hVersion', mysql.CHAR(length=11), nullable=True),
    sa.Column('mappingCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('result', mysql.ENUM('Genuine', 'Counterfeit', 'Revalidation', 'Exprired', 'Invalid', 'Retry', 'OverCert', 'DifferentQR', 'CommonQR', 'NotiOverCert'), nullable=False),
    sa.Column('resultDetail', mysql.INTEGER(display_width=4), nullable=True),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown', 'Web'), nullable=False),
    sa.Column('dtCertificate', mysql.DATETIME(), nullable=False),
    sa.Column('longitude', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('regionIdx', mysql.BIGINT(display_width=10), nullable=False),
    sa.Column('random', mysql.CHAR(length=16), nullable=True),
    sa.Column('randomCnt', mysql.INTEGER(display_width=10), nullable=True),
    sa.Column('retailerID', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('mode', mysql.ENUM('V', 'P'), nullable=True),
    sa.Column('data', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.ForeignKeyConstraint(['hVersion'], ['td_tag_version.version'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('ts_appdown_daily',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', mysql.CHAR(length=8), nullable=False),
    sa.Column('companyCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown'), nullable=False),
    sa.Column('tagType', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG'), nullable=True),
    sa.Column('downloadCount', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_ts_appdown_daily_companyCode'), 'ts_appdown_daily', ['companyCode'], unique=False)
    op.create_table('td_device',
    sa.Column('idx', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('pushToken', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('osVersion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('appVersion', mysql.CHAR(length=11), nullable=False),
    sa.Column('appCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('appTagType', mysql.CHAR(length=1), nullable=False),
    sa.Column('agreeTerm', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('agreeGPS', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('useBackground', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('languageCode', mysql.ENUM('Korean', 'English', 'Chinese'), nullable=True),
    sa.Column('serverName', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('dtLastConnected', mysql.DATETIME(), nullable=False),
    sa.Column('dtTermAgreement', mysql.DATETIME(), nullable=True),
    sa.Column('serviceTermVersion', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('locationTermVersion', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ipAddr', mysql.VARCHAR(length=24), nullable=True),
    sa.ForeignKeyConstraint(['appCode'], ['td_app.code'], ),
    sa.ForeignKeyConstraint(['locationTermVersion'], ['td_location_term.version'], ),
    sa.ForeignKeyConstraint(['serviceTermVersion'], ['td_service_term.version'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('pushToken')
    )
    op.create_index(op.f('ix_td_device_appCode'), 'td_device', ['appCode'], unique=False)
    op.create_index(op.f('ix_td_device_locationTermVersion'), 'td_device', ['locationTermVersion'], unique=False)
    op.create_index(op.f('ix_td_device_serviceTermVersion'), 'td_device', ['serviceTermVersion'], unique=False)
    op.create_index(op.f('ix_td_device_model'), 'td_device', ['model'], unique=False)
    op.create_table('ti_holotag',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('tagIdx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('path', mysql.TEXT(), nullable=False),
    sa.Column('state', mysql.ENUM('Registered', 'Deleted', 'Paused'), nullable=False),
    sa.Column('registarant', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('dtRegistered', mysql.DATETIME(), nullable=False),
    sa.Column('modifier', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('dtModified', mysql.DATETIME(), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['modifier'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['registarant'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['tagIdx'], ['td_holotag.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_ti_holotag_tagIdx'), 'ti_holotag', ['tagIdx'], unique=False)
    op.create_index(op.f('ix_ti_holotag_modifier'), 'ti_holotag', ['modifier'], unique=False)
    op.create_index(op.f('ix_ti_holotag_registarant'), 'ti_holotag', ['registarant'], unique=False)
    op.create_table('th_report',
    sa.Column('idx', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('deviceID', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('companyCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('tagCode', mysql.CHAR(length=10), nullable=True),
    sa.Column('hVersion', mysql.CHAR(length=11), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=False),
    sa.Column('imageProduct', mysql.TEXT(), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('dtCreated', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('contactType', mysql.ENUM('CONTACT_NUM', 'WECHAT', 'LINE', 'KAKAOTALK'), nullable=True),
    sa.Column('purchasePlace', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('onlinePurchasePlace', mysql.VARCHAR(length=220), nullable=True),
    sa.Column('purchaseDate', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('type', mysql.ENUM('Report', 'Expire', 'Share', 'Invalid'), nullable=False),
    sa.Column('tagType', mysql.ENUM('HOLOTAG_ONLY', 'HOLOTAG_BARCODE', 'HYBRIDTAG', 'RANDOMTAG', 'SQRTAG'), nullable=True),
    sa.Column('mappingCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('random', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('retailerID', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('state', mysql.ENUM('Question', 'Answer', 'Holding'), nullable=False),
    sa.Column('answerer', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dtAnswer', mysql.DATETIME(), nullable=True),
    sa.Column('aContent', mysql.TEXT(), nullable=True),
    sa.Column('osType', mysql.ENUM('iOS', 'Android', 'Unknown'), nullable=False),
    sa.Column('memo', mysql.TEXT(), nullable=True),
    sa.Column('certificationIdx', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('importantYN', mysql.ENUM('Y', 'N'), nullable=False),
    sa.Column('codeState', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('codeChannel', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('resultDetail', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('data', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['answerer'], ['td_admin.id'], ),
    sa.ForeignKeyConstraint(['companyCode'], ['td_company.code'], ),
    sa.ForeignKeyConstraint(['deviceID'], ['td_device.pushToken'], ),
    sa.ForeignKeyConstraint(['hVersion'], ['td_tag_version.version'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_th_report_companyCode'), 'th_report', ['companyCode'], unique=False)
    op.create_index(op.f('ix_th_report_deviceID'), 'th_report', ['deviceID'], unique=False)
    op.create_index(op.f('ix_th_report_dtCreated'), 'th_report', ['dtCreated'], unique=False)
    op.create_index(op.f('ix_th_report_tagCode'), 'th_report', ['tagCode'], unique=False)
    op.create_index(op.f('ix_th_report_answerer'), 'th_report', ['answerer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_th_report_answerer'), table_name='th_report')
    op.drop_index(op.f('ix_th_report_tagCode'), table_name='th_report')
    op.drop_index(op.f('ix_th_report_dtCreated'), table_name='th_report')
    op.drop_index(op.f('ix_th_report_deviceID'), table_name='th_report')
    op.drop_index(op.f('ix_th_report_companyCode'), table_name='th_report')
    op.drop_table('th_report')
    op.drop_index(op.f('ix_ti_holotag_registarant'), table_name='ti_holotag')
    op.drop_index(op.f('ix_ti_holotag_modifier'), table_name='ti_holotag')
    op.drop_index(op.f('ix_ti_holotag_tagIdx'), table_name='ti_holotag')
    op.drop_table('ti_holotag')
    op.drop_index(op.f('ix_td_device_model'), table_name='td_device')
    op.drop_index(op.f('ix_td_device_serviceTermVersion'), table_name='td_device')
    op.drop_index(op.f('ix_td_device_locationTermVersion'), table_name='td_device')
    op.drop_index(op.f('ix_td_device_appCode'), table_name='td_device')
    op.drop_table('td_device')
    op.drop_index(op.f('ix_ts_appdown_daily_companyCode'), table_name='ts_appdown_daily')
    op.drop_table('ts_appdown_daily')
    op.drop_table('th_certification')
    op.drop_index(op.f('ix_td_retailer_rtid'), table_name='td_retailer')
    op.drop_index(op.f('ix_td_retailer_companyCode'), table_name='td_retailer')
    op.drop_table('td_retailer')
    op.drop_index(op.f('ix_td_holotag_registrant'), table_name='td_holotag')
    op.drop_index(op.f('ix_td_holotag_modifier'), table_name='td_holotag')
    op.drop_index(op.f('ix_td_holotag_mappingCode'), table_name='td_holotag')
    op.drop_index(op.f('ix_td_holotag_hVersion'), table_name='td_holotag')
    op.drop_index(op.f('ix_td_holotag_companyCode'), table_name='td_holotag')
    op.drop_table('td_holotag')
    op.drop_index(op.f('ix_td_app_registrant'), table_name='td_app')
    op.drop_index(op.f('ix_td_app_modifier'), table_name='td_app')
    op.drop_index(op.f('ix_td_app_code'), table_name='td_app')
    op.drop_index(op.f('ix_td_app_companyCode'), table_name='td_app')
    op.drop_table('td_app')
    op.drop_index(op.f('ix_td_account_role'), table_name='td_account')
    op.drop_index(op.f('ix_td_account_phone'), table_name='td_account')
    op.drop_index(op.f('ix_td_account_name_kr'), table_name='td_account')
    op.drop_index(op.f('ix_td_account_companyCode'), table_name='td_account')
    op.drop_table('td_account')
    op.drop_table('td_tag_version')
    op.drop_index(op.f('ix_td_company_registrant'), table_name='td_company')
    op.drop_index(op.f('ix_td_company_modifier'), table_name='td_company')
    op.drop_table('td_company')
    op.drop_table('td_banner')
    op.drop_index(op.f('ix_td_admin_role'), table_name='td_admin')
    op.drop_table('td_admin')
    op.drop_index(op.f('ix_ts_cert_report_count_type'), table_name='ts_cert_report_count')
    op.drop_index(op.f('ix_ts_cert_report_count_date'), table_name='ts_cert_report_count')
    op.drop_index(op.f('ix_ts_cert_report_count_tagCode'), table_name='ts_cert_report_count')
    op.drop_index(op.f('ix_ts_cert_report_count_osType'), table_name='ts_cert_report_count')
    op.drop_index(op.f('ix_ts_cert_report_count_companyCode'), table_name='ts_cert_report_count')
    op.drop_table('ts_cert_report_count')
    op.drop_index(op.f('ix_ts_active_unique_count_date'), table_name='ts_active_unique_count')
    op.drop_index(op.f('ix_ts_active_unique_count_osType'), table_name='ts_active_unique_count')
    op.drop_index(op.f('ix_ts_active_unique_count_companyCode'), table_name='ts_active_unique_count')
    op.drop_table('ts_active_unique_count')
    op.drop_table('tl_login')
    op.drop_table('td_service_term')
    op.drop_index(op.f('ix_td_model_name'), table_name='td_model')
    op.drop_index(op.f('ix_td_model_osType'), table_name='td_model')
    op.drop_table('td_model')
    op.drop_table('td_location_term')
    op.drop_index(op.f('ix_td_black_list_idx'), table_name='td_black_list')
    op.drop_table('td_black_list')
    op.drop_table('tc_role')
    op.drop_table('tc_result')
    # ### end Alembic commands ###
